/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class java_jni_Example */

#ifndef _Included_jni_example_Example
#define _Included_jni_example_Example
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jni_example_Example
 * Method:    sq
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_jni_example_Example_sq(JNIEnv *, jclass, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
